import React, { useEffect } from 'react'
import { CalendarDays, Bot, BarChart3, Flag, Zap, Shield, Check, ArrowRight, ChevronRight } from 'lucide-react'

const FEATURES = [
  {
    Icon: CalendarDays,
    title: 'Smart Calendar',
    desc: 'Visualise your swim, bike, and run sessions on a drag-and-drop weekly calendar.',
  },
  {
    Icon: Bot,
    title: 'AI Coach',
    desc: 'Get a personalised training week generated by AI based on your fitness, goals, and history.',
  },
  {
    Icon: BarChart3,
    title: 'Dashboard Analytics',
    desc: 'Track volume, RPE trends, sport balance, and weekly progress at a glance.',
  },
  {
    Icon: Flag,
    title: 'Race Countdown',
    desc: 'Set your target race and watch Strelo periodise your training around it.',
  },
  {
    Icon: Zap,
    title: 'Workout Builder',
    desc: 'Build structured intervals and brick sessions with a visual drag-and-drop builder.',
  },
  {
    Icon: Shield,
    title: 'Injury Aware',
    desc: 'Log limitations and injuries — the AI adapts your plan to keep you safe.',
  },
]

const FREE_FEATURES = [
  'Log workouts & races',
  'Calendar view',
  'Dashboard stats',
  'Basic athlete profile',
]

const PRO_FEATURES = [
  'Everything in Free',
  'AI Coach — personalised weekly plans',
  'Advanced analytics & trends',
  'Unlimited race tracking',
  'Priority support',
]

export default function LandingPage({ onGetStarted, onSignIn, onNavigate }) {
  // Wake up the backend while user reads the landing page
  useEffect(() => {
    fetch((import.meta.env.VITE_API_URL || 'http://localhost:8000') + '/health').catch(() => {})
  }, [])

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Nav */}
      <header className="sticky top-0 z-40 bg-white/80 backdrop-blur-lg border-b border-slate-100">
        <div className="max-w-5xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 shadow-lg shadow-indigo-500/25 flex items-center justify-center">
              <svg width="18" height="18" viewBox="0 0 18 18" fill="none">
                <path d="M5 14L8 4" stroke="white" strokeWidth="2.2" strokeLinecap="round"/>
                <path d="M8.5 14L11.5 4" stroke="rgba(255,255,255,0.6)" strokeWidth="2.2" strokeLinecap="round"/>
                <path d="M12 14L15 4" stroke="rgba(255,255,255,0.3)" strokeWidth="2.2" strokeLinecap="round"/>
              </svg>
            </div>
            <span className="font-black text-slate-800 text-lg tracking-tight">Strelo</span>
          </div>
          <div className="flex items-center gap-3">
            <button onClick={onSignIn}
              className="text-sm font-semibold text-slate-500 hover:text-slate-800 transition-colors">
              Sign In
            </button>
            <button onClick={onGetStarted}
              className="text-sm font-bold text-white bg-gradient-to-r from-indigo-500 to-violet-600 px-4 py-2 rounded-xl hover:opacity-90 transition-all shadow-sm">
              Get Started Free
            </button>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="max-w-5xl mx-auto px-4 pt-20 pb-24 text-center">
        <div className="inline-flex items-center gap-1.5 bg-indigo-50 text-indigo-600 text-xs font-bold px-3 py-1.5 rounded-full mb-6">
          <Zap size={12} strokeWidth={2.5} />
          AI-Powered Training
        </div>
        <h1 className="text-4xl sm:text-5xl md:text-6xl font-black text-slate-900 leading-tight tracking-tight">
          Train smarter for<br />
          <span className="bg-gradient-to-r from-indigo-500 to-violet-600 bg-clip-text text-transparent">
            your next triathlon
          </span>
        </h1>
        <p className="text-slate-500 text-lg mt-5 max-w-xl mx-auto leading-relaxed">
          Strelo combines an AI coach with a beautiful training planner to help you
          swim, bike, and run your way to race day — prepared and confident.
        </p>
        <div className="flex items-center justify-center gap-3 mt-8">
          <button onClick={onGetStarted}
            className="text-sm font-bold text-white bg-gradient-to-r from-indigo-500 to-violet-600 px-6 py-3 rounded-2xl hover:opacity-90 transition-all shadow-lg shadow-indigo-500/25 flex items-center gap-2">
            Start Free <ArrowRight size={16} strokeWidth={2} />
          </button>
          <button onClick={onSignIn}
            className="text-sm font-bold text-slate-600 bg-white border border-slate-200 px-6 py-3 rounded-2xl hover:border-slate-300 transition-all flex items-center gap-2">
            Sign In <ChevronRight size={16} strokeWidth={2} />
          </button>
        </div>
        <p className="text-xs text-slate-400 mt-4">No credit card required</p>
      </section>

      {/* Features */}
      <section className="bg-white border-y border-slate-100 py-20">
        <div className="max-w-5xl mx-auto px-4">
          <div className="text-center mb-14">
            <p className="text-xs font-bold text-indigo-500 uppercase tracking-widest mb-2">Features</p>
            <h2 className="text-3xl font-black text-slate-800">Everything you need to race-ready</h2>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {FEATURES.map(({ Icon, title, desc }) => (
              <div key={title} className="bg-slate-50 rounded-2xl p-6 hover:shadow-md transition-shadow">
                <div className="w-10 h-10 rounded-xl bg-indigo-100 flex items-center justify-center mb-4">
                  <Icon size={20} strokeWidth={1.5} className="text-indigo-600" />
                </div>
                <h3 className="font-bold text-slate-800 mb-1">{title}</h3>
                <p className="text-sm text-slate-500 leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="py-20">
        <div className="max-w-5xl mx-auto px-4">
          <div className="text-center mb-14">
            <p className="text-xs font-bold text-indigo-500 uppercase tracking-widest mb-2">Pricing</p>
            <h2 className="text-3xl font-black text-slate-800">Simple, transparent pricing</h2>
            <p className="text-slate-500 text-sm mt-2">Start free. Upgrade when you're ready for AI coaching.</p>
          </div>
          <div className="grid md:grid-cols-2 gap-6 max-w-2xl mx-auto">
            {/* Free */}
            <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-7">
              <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">Free</p>
              <p className="text-4xl font-black text-slate-800 mt-2">$0</p>
              <p className="text-slate-400 text-sm">Forever</p>
              <ul className="mt-6 space-y-3">
                {FREE_FEATURES.map(f => (
                  <li key={f} className="flex items-center gap-2.5 text-sm text-slate-600">
                    <Check size={16} strokeWidth={2.5} className="text-slate-400 shrink-0" />
                    {f}
                  </li>
                ))}
              </ul>
              <button onClick={onGetStarted}
                className="w-full mt-7 py-2.5 rounded-xl text-sm font-bold border-2 border-slate-200 text-slate-600 hover:border-slate-300 transition-all">
                Get Started
              </button>
            </div>

            {/* Pro */}
            <div className="bg-white rounded-2xl border-2 border-indigo-400 shadow-sm p-7 relative">
              <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-indigo-500 text-white text-xs font-bold px-3 py-1 rounded-full">
                Most Popular
              </div>
              <div className="flex items-center gap-2">
                <p className="text-xs font-bold text-indigo-500 uppercase tracking-widest">Pro</p>
                <Zap size={14} strokeWidth={2.5} className="text-indigo-500" />
              </div>
              <div className="mt-2 flex items-baseline gap-3">
                <div>
                  <p className="text-4xl font-black text-slate-800">$12.99</p>
                  <p className="text-slate-400 text-sm">/month</p>
                </div>
                <div className="text-slate-200">|</div>
                <div>
                  <p className="text-2xl font-black text-slate-800">$123.99</p>
                  <p className="text-slate-400 text-sm">/year <span className="text-emerald-500 font-bold">Save 20%</span></p>
                </div>
              </div>
              <ul className="mt-6 space-y-3">
                {PRO_FEATURES.map(f => (
                  <li key={f} className="flex items-center gap-2.5 text-sm text-slate-600">
                    <Check size={16} strokeWidth={2.5} className="text-indigo-500 shrink-0" />
                    {f}
                  </li>
                ))}
              </ul>
              <button onClick={onGetStarted}
                className="w-full mt-7 py-2.5 rounded-xl text-sm font-bold text-white bg-gradient-to-r from-indigo-500 to-violet-600 hover:opacity-90 transition-all shadow-sm">
                Start Free, Upgrade Later
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 py-20">
        <div className="max-w-5xl mx-auto px-4 text-center">
          <h2 className="text-3xl font-black text-white">Ready to train smarter?</h2>
          <p className="text-white/50 mt-3 max-w-md mx-auto">
            Join athletes using Strelo to plan, track, and optimise their triathlon training.
          </p>
          <button onClick={onGetStarted}
            className="mt-8 text-sm font-bold text-indigo-600 bg-white px-6 py-3 rounded-2xl hover:bg-slate-50 transition-all shadow-lg flex items-center gap-2 mx-auto">
            Get Started Free <ArrowRight size={16} strokeWidth={2} />
          </button>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-slate-900 border-t border-white/5 py-8">
        <div className="max-w-5xl mx-auto px-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-lg bg-gradient-to-br from-indigo-500 to-violet-600 flex items-center justify-center">
              <svg width="12" height="12" viewBox="0 0 18 18" fill="none">
                <path d="M5 14L8 4" stroke="white" strokeWidth="2.2" strokeLinecap="round"/>
                <path d="M8.5 14L11.5 4" stroke="rgba(255,255,255,0.6)" strokeWidth="2.2" strokeLinecap="round"/>
                <path d="M12 14L15 4" stroke="rgba(255,255,255,0.3)" strokeWidth="2.2" strokeLinecap="round"/>
              </svg>
            </div>
            <span className="font-bold text-white/50 text-sm">Strelo</span>
          </div>
          <div className="flex items-center gap-4">
            <button onClick={() => onNavigate('privacy')} className="text-white/30 text-xs hover:text-white/60 transition-colors">Privacy</button>
            <button onClick={() => onNavigate('terms')} className="text-white/30 text-xs hover:text-white/60 transition-colors">Terms</button>
            <span className="text-white/30 text-xs">&copy; 2026 Strelo</span>
          </div>
        </div>
      </footer>
    </div>
  )
}
